language: python
python:
  - "3.6.9"
install:
  - pip3 -V
  - pip3 install --progress-bar off -r source/requirements_prod.txt

  - pip3 list
  - pip3 install --progress-bar  off -r tests/requirements.txt

script:
  - export PYTHONPATH=./src
  - pytest --tb=short

